name: SSO Client App CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: sso-client

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.set-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Generate image tag
        id: gen_tag
        run: |
          ts=$(date +'%Y%m%d-%H%M%S')
          echo "IMAGE_TAG=$(git rev-parse --short HEAD)_$ts" >> $GITHUB_OUTPUT
          echo "Generated image tag ${{ steps.set-tag.outputs.IMAGE_TAG }}"
  
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    # - name: Generate image tag
    #   run: |
    #       echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    #       echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        
    - name: Build and Push Docker image
      # uses: mr-smithers-excellent/docker-build-push@v6
      # with:
      #   image: a1super/sso-client
      #   registry: docker.io
      #   username: ${{ secrets.DOCKER_HUB_USER }}
      #   password: ${{ secrets.DOCKER_HUB_TOKEN }}
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_HUB_USER}}/$IMAGE_NAME:${{ needs.setup.outputs.IMAGE_TAG }}

              
      
