name: SSO Client App CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: ${{secrets.REGISTRY_URL}}/sso/sso-test-client
        tags: latest
        dockerfile: ./Dockerfile
        registry: ${{secrets.REGISTRY_URL}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

              
      
