name: SSO Client App CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: sso-client

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.gen_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Generate image tag
        id: gen_tag
        run: |
          ts=$(date +'%Y%m%d_%H%M%S')
          echo "IMAGE_TAG=${GITHUB_SHA::8}_$ts" >> $GITHUB_OUTPUT
  
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKER_HUB_USER}}/sso-client:${{ needs.setup.outputs.IMAGE_TAG }}
    
  deploy:
      runs-on: ubuntu-latest
      needs: [setup, build]
      steps:
        - name: SSH Login
          uses: appleboy/ssh-action@v1.2.2
          with:
            host: ${{ secrets.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.REMOTE_SSH_KEY }}
            script: |
              docker pull {{ secrets.DOCKER_HUB_USER }}/sso-client:${{ needs.setup.outputs.IMAGE_TAG }}

      
      
