name: SSO Client App CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: a1super/github-actions-demo-app
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

              
      
